# Item to use as currency: must be a minecraft item, ALL CAPS.
currency-item: ECHO_SHARD

# min cooldown for each bet. applies to all games.
bet-cooldown-ms: 750

# on FIRST init, this is the starting bankroll balance. you can edit it before launching casino the first time.
# If you prefer so, you can delete the database (.db) file and wipe everything to start from scratch again.
house-starting-bankroll: 0

# If a game is against the house (example: slots) you can specify the edge the house gets here. 
# 0 means completely fair odds. 0.02 means 98% fair odds, aka 2% edge for the house.
# Duels ignore this.
house-edge: 0.02

# config for max-min bets and enabling/disabling. Ignore if you're here for the shop.
games:
  roulette:
    min-bet: 1
    max-bet: 64
    enabled: true
  slots:
    min-bet: 1
    max-bet: 32
    enabled: true
  blackjack:
    min-bet: 1
    max-bet: 64
    enabled: true
  coinflip:
    min-bet: 1
    max-bet: 128
    enabled: true
  mines:
    min-bet: 1
    max-bet: 32
    enabled: true
  hilo:
    min-bet: 1
    max-bet: 32
    enabled: true
  shop:
    enabled: true

# Database file name! (sqlite)
database:
  file: casino.db

# Minimum and maximum daily reward, as well as its cooldown in hours
daily-reward:
  min: 2
  max: 5
  cooldown-hours: 24

# Shop config: 
# id: identifier inside the plugin (ex. water_bucket)
# material: ACTUAL minecraft item, all caps: (WATER_BUCKET)
# name: self explanatory
# price: same
# amount: same
# lore: extra information 
# permission: if you want me to add a special permission for it
# example config: 
# id: water_bucket
# name: "Water Bucket"
# price: 1
# amount: 2
# permission: casino.shop.waterbucket
# lore:
#     - "Extra information about the item"
#     - "Possibly multiple lines if you do it like this"
shop:
  items:
    - id: diamond
      material: DIAMOND
      name: "Diamond"
      price: 1
      amount: 6
    - id: netherite_scrap
      material: NETHERITE_SCRAP
      name: "Netherite Scrap"
      price: 1
      amount: 1
    - id: totem
      material: TOTEM_OF_UNDYING
      name: "Totem of Undying"
      price: 5
      amount: 1
    - id: gold_block
      material: GOLD_BLOCK
      name: "Block of Gold"
      price: 1
      amount: 3
    - id: enchanted_golden_apple
      material: ENCHANTED_GOLDEN_APPLE
      name: "Enchanted Golden Apple"
      price: 4
      amount: 1
    - id: obsidian
      material: OBSIDIAN
      name: "Obsidian"
      price: 1
      amount: 12
    - id: trident
      material: TRIDENT
      name: "Trident"
      price: 8
      amount: 1
    - id: heavy_core
      material: HEAVY_CORE
      name: "Heavy Core"
      price: 12
      amount: 1
    - id: diamond_horse_armor
      material: DIAMOND_HORSE_ARMOR
      name: "Diamond Horse Armor"
      price: 2
      amount: 1
    - id: diamond_nautilus_armor
      material: DIAMOND_NAUTILUS_ARMOR
      name: "Diamond Nautilus Armor"
      price: 2
      amount: 1
    - id: sand
      material: SAND
      name: "Sand"
      price: 8
      amount: 2304
