name: Casino
version: '1.3.6'
main: net.mercdev.casino.core.CasinoPlugin
api-version: '1.21'
author: 1mercdev
description: Multi-game casino framework (roulette, slots, blackjack, coinflip, mines, hilo)

commands:
  casino:
    description: Open the casino menu || manage your chip balance
    usage: /casino [balance|deposit <amount>|withdraw <amount>|daily|admin]
  bhunt:
    description: Open the bounty-hunt GUI || View and manage your bounties
    usage: /bhunt

permissions:
  casino.use:
    description: Allows playing casino games and managing your chip balance
    default: true
  casino.others.balance:
    description: Allows you to view other user's balance.
    default: op
  casino.admin:
    description: Allows viewing and topping up the house bankroll
    default: op
